### ISSUE TITLE
Error in muCNV genotype

### ISSUE THREAD

**Issue by zihhuafang** [gjun/muCNV#10]
Hi @gjun , 

Thanks for developing this tool. 
I am trying it out on my WGS data with the following steps and got the error I don't understand.

1. I merged parliament2-called sv from samples by SURVIVOR: `SURVIVOR merge $survivor_inputs 200 1 1 0 0 10 tmp.vcf`
2. Generating vcf interval: `muCNV vcf2int -v tmp.vcf -i candidate_sv.interavls`
3. Generating pileup for each sample: `muCNV pileup -s ${sample} -V candidate_sv.interavls -b ${input_cram} -f /muCNV/resource/GRCh38.v3.gc -o pileup/${sample}`
4. When I performed muCNV genotype after generating the list of pileups: `muCNV genotype -V /muCNV/resource/GRCh38.v3.gc  -i pileup.list -f /muCNV/resource/GRCh38.v3.gc -o ${output_prefix}`

I got the following the error:

GC content initialized
91561 SVs loaded from input file
418 items exist in the index file pileup.list
418 pileup files identified from index file
Error! number of samples in pileup and vars do not match: pileup/sample1

This is the first sample in the pileup list.
I double checked the directory pileup/sample1 did exist, so I don't really understand the error.
Could you advice me how to trouble shoot?

Appreciate your input.
Zih-Hua

**Comment by zihhuafang** [comment]
I decided to play around making the pileup list.
As it turned out, the issue was the list.

My pileup was created in a sample directory: pileup/sample1/sample1.*. 
By listing pileup/sample1, it doesn't work.

After making the correct pileup list, muCNV works.

**Comment by quanc1989** [comment]
@zihhuafang Hi, I came across the same exception.

Could you please tell me how you correct the "pileup.list" file which is the input of "muCNV genotype -i"?

Thanks a  lot
