### ISSUE TITLE
muCNV gcidx doesn't work with reference FASTA files where chromosome names don't have 'chr' prefix

### ISSUE THREAD

**Issue by vladimirtomic** [gjun/muCNV#3]
muCNV gcidx works well with reference FASTA files where chromosome names are prefixed with 'chr' (GRCh38_primary_assembly_plus_ebv_alt_decoy_hla.fasta, ucsc.hg19.fasta, hs38DH.fa), but throws:

`Floating point exception (core dumped)`

when chromosome names are not prefixed with 'chr' (human_g1k_v37_decoy.fasta, GRCh38ERCC.ensembl97.fasta, HG19_Broad_variant.fasta).

I'm not sure if this affects other tools in the toolkit since `reference.gc` is a required input file for other tools in the toolkit.

**Comment by gjun** [comment]
This has been fixed.
